### ISSUE TITLE
Getting Error Running Example Code

### ISSUE THREAD

**Issue by tim-o-nicholson** [rubenjgarcia/jdbc-metadata#1]
I tried to connect to my local SQL Server database using your example code to list all the tables, and I'm getting the following error:
```
PS C:\Users\tim.BEDROCK\Informer5> node .\jdbcMetadata.js
Getting tables
C:\Users\tim.BEDROCK\Informer5\node_modules\jdbc-metadata\index.js:46
    java.callMethod(self._conn, 'getMetaData', function (err, metadata) {
         ^

TypeError: Argument 1 must be an object
    at TypeError (native)
    at getMetadata (C:\Users\tim.BEDROCK\Informer5\node_modules\jdbc-metadata\index.js:46:10)
    at JDBCMetadata.metadata (C:\Users\tim.BEDROCK\Informer5\node_modules\jdbc-metadata\index.js:37:16)
    at JDBCMetadata.tables (C:\Users\tim.BEDROCK\Informer5\node_modules\jdbc-metadata\index.js:60:14)
    at C:\Users\tim.BEDROCK\Informer5\jdbcMetadata.js:16:18
    at C:\Users\tim.BEDROCK\Informer5\node_modules\jdbc-metadata\index.js:23:24
    at C:\Users\tim.BEDROCK\Informer5\node_modules\jdbc-metadata\lib\jdbc.js:18:20
    at JDBCConn.initialize (C:\Users\tim.BEDROCK\Informer5\node_modules\jdbc-metadata\lib\jdbc.js:16:10)
    at JDBCMetadata.metadata (C:\Users\tim.BEDROCK\Informer5\node_modules\jdbc-metadata\index.js:21:20)
    at Object.<anonymous> (C:\Users\tim.BEDROCK\Informer5\jdbcMetadata.js:13:14)
```
My code is as follows:
```
var metadata = require('jdbc-metadata');

var jdbcConfig = {
    libpath: __dirname + '/lib/sqljdbc4-4.0.2206.100',
    drivername: 'com.microsoft.sqlserver.jdbc.SQLServerDriver',
    url: 'jdbc:sqlserver://localhost:1433;databaseName=AdventureWorks2008',
    user: 'sa',
    password: 'REDACTED'
};

var jdbcMetadata = new metadata(jdbcConfig);

jdbcMetadata.metadata(function (err, metadata) {
    console.log('Getting tables');
    jdbcMetadata.tables(null, function (err, tables){
        console.log('Here are the tables:');
        console.log(tables);

        jdbcMetadata.close(function(err){
            console.log('Connection closed');
        })
    });
});
```

**Comment by rubenjgarcia** [comment]
What version of Node are you using?

**Comment by deimigodultimate2015** [comment]
Your libpath not point to your JDBC since '/lib/sqljdbc4-4.0.2206.100' must have '.jdbc' at the end to be a jdbc file
